# Raw Data Exploratory Data Analysis

This notebook inspects the raw GEO files before data wrangling.

The aim is to understand the structure of the expression matrix and metadata file, verify how samples are represented, and confirm that sample descriptions from the series matrix match the sample columns in the expression matrix.

In [1]:
#IMPORTS
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#SET FILE PATHS
series_file = "../data/raw_data/GSE147379_series_matrix.txt"
expression_file = "../data/raw_data/GSE147379_Corton_29_Chem_data_matrix.txt"

In [ ]:
#LOAD EXPRESSION MATRIX & INSPECT STRUCTURE
expression = pd.read_csv(expression_file, sep="\t")
expression.head()

,ID_REF,Corton-1-Rat-Primary_A07,Corton-1-Rat-Primary_A08,Corton-1-Rat-Primary_A09,Corton-1-Rat-Primary_A10,Corton-1-Rat-Primary_A11,Corton-1-Rat-Primary_A12,Corton-1-Rat-Primary_B01,Corton-1-Rat-Primary_B02,Corton-1-Rat-Primary_B03,...,Corton-3-Rat-Primary_A09,Corton-3-Rat-Primary_A10,Corton-3-Rat-Primary_A11,Corton-3-Rat-Primary_A12,Corton-3-Rat-Primary_B01,Corton-3-Rat-Primary_B02,Corton-3-Rat-Primary_B03,Corton-3-Rat-Primary_B04,Corton-3-Rat-Primary_B05,Corton-3-Rat-Primary_B06
0,1190003K10Rik1_53417,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1700007B14Rik_48912,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1700016D06Rik_50928,0,0,0,0,0,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1700020N01Rik0.7_53590,1,4,0,3,3,1,2,1,0,...,6,1,4,3,0,1,0,3,4,5
4,1700025F22Rik_44725,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

In [8]:
#CHECK EXPRESSION MATRIX SHAPE
expression.shape

(22253, 193)

In [9]:
expression.columns[:10]

Index(['ID_REF', 'Corton-1-Rat-Primary_A07', 'Corton-1-Rat-Primary_A08',
       'Corton-1-Rat-Primary_A09', 'Corton-1-Rat-Primary_A10',
       'Corton-1-Rat-Primary_A11', 'Corton-1-Rat-Primary_A12',
       'Corton-1-Rat-Primary_B01', 'Corton-1-Rat-Primary_B02',
       'Corton-1-Rat-Primary_B03'],
      dtype='str')

In [10]:
#COLUMNS [1:] - REPRESENT SAMPLES
sample_columns = expression.columns[1:]

print("First 10 sample columns:")
print(sample_columns[:10])

First 10 sample columns:
Index(['Corton-1-Rat-Primary_A07', 'Corton-1-Rat-Primary_A08',
       'Corton-1-Rat-Primary_A09', 'Corton-1-Rat-Primary_A10',
       'Corton-1-Rat-Primary_A11', 'Corton-1-Rat-Primary_A12',
       'Corton-1-Rat-Primary_B01', 'Corton-1-Rat-Primary_B02',
       'Corton-1-Rat-Primary_B03', 'Corton-1-Rat-Primary_B04'],
      dtype='str')

In [12]:
expression.dtypes.head()

ID_REF                        str
Corton-1-Rat-Primary_A07    int64
Corton-1-Rat-Primary_A08    int64
Corton-1-Rat-Primary_A09    int64
Corton-1-Rat-Primary_A10    int64
dtype: object

In [ ]:
#CHECK EXPRESSION VALUE TYPE FOR SAMPLES
expression[sample_columns].dtypes.value_counts()

int64    192
Name: count, dtype: int64

In [ ]:
#CHECK FOR MISSING VALUES
print("Total missing values:", expression.isna().sum().sum())

Total missing values: 0

In [ ]:
#CHECK GENE ID NAME COLUMN
expression["ID_REF"].head(20)

0             1190003K10Rik1_53417
1              1700007B14Rik_48912
2              1700016D06Rik_50928
3           1700020N01Rik0.7_53590
4              1700025F22Rik_44725
5              1700066B19Rik_53634
6              1700069L16Rik_47688
7              1700092M07Rik_38887
8              2310003L06Rik_48893
9         3100002H09Rik0.049_48329
10             3110082J24Rik_81547
11    3110082J24Rik0.0009604_47167
12             4930513O06Rik_35669
13             4930596D02Rik_45659
14             4931400O07Rik_42655
15             4933416C03Rik_36365
16             4933427I04Rik_44550
17             4933428G20Rik_50086
18             4933436I01Rik_49866
19             7420426K07Rik_39944
Name: ID_REF, dtype: str

In [17]:
#CHECK FOR TARGET GENE
target_gene = "Acot1_7968"

target_gene in expression["ID_REF"].values

True

In [ ]:
#INSPECT TARGET GENE EXPRESISON VALUES FOR SAMPLES
expression[expression["ID_REF"] == target_gene]

,ID_REF,Corton-1-Rat-Primary_A07,Corton-1-Rat-Primary_A08,Corton-1-Rat-Primary_A09,Corton-1-Rat-Primary_A10,Corton-1-Rat-Primary_A11,Corton-1-Rat-Primary_A12,Corton-1-Rat-Primary_B01,Corton-1-Rat-Primary_B02,Corton-1-Rat-Primary_B03,...,Corton-3-Rat-Primary_A09,Corton-3-Rat-Primary_A10,Corton-3-Rat-Primary_A11,Corton-3-Rat-Primary_A12,Corton-3-Rat-Primary_B01,Corton-3-Rat-Primary_B02,Corton-3-Rat-Primary_B03,Corton-3-Rat-Primary_B04,Corton-3-Rat-Primary_B05,Corton-3-Rat-Primary_B06
1526,Acot1_7968,2,1,9,2,0,3,2,3,3,...,0,3,3,0,0,1,0,1,5,3

In [20]:
#READ SERIES METADATA FILE
with open(series_file, errors="ignore") as f:
    reader = csv.reader(f, delimiter="\t")
    rows = list(reader)

In [21]:
#EXTRACT SAMPLE METADATA- CHEMICAL, DOSE, SAMPLE NAME (LATER USED TO FIND EXPRESSION VALS)
sample_desc = None
sample_chem_row = None
sample_dose_row = None

for row in rows:
    if len(row) > 0 and row[0] == "!Sample_description":
        sample_desc = row[1:]
        break

for row in rows:
    if len(row) > 1 and row[0] == "!Sample_characteristics_ch1":
        if row[1].lower().startswith("chemical:"):
            sample_chem_row = row[1:]
            break

for row in rows:
    if len(row) > 1 and row[0] == "!Sample_characteristics_ch1":
        if row[1].lower().startswith("dose:"):
            sample_dose_row = row[1:]
            break

The sample description row was extracted because it contains the sample names used as column headers in the expression matrix. The chemical and dose rows were extracted to identify the exposure condition for each sample.

In [22]:
#INSPECT METADATA VALUES
print("Sample descriptions:")
print(sample_desc[:5])

print("\nChemical row:")
print(sample_chem_row[:5])

print("\nDose row:")
print(sample_dose_row[:5])

Sample descriptions:
['Corton-1-Rat-Primary_A07', 'Corton-1-Rat-Primary_A08', 'Corton-1-Rat-Primary_A09', 'Corton-1-Rat-Primary_A10', 'Corton-1-Rat-Primary_A11']

Chemical row:
['chemical: triclosan', 'chemical: triclosan', 'chemical: triclosan', 'chemical: triclosan', 'chemical: triclosan']

Dose row:
['dose: 33.3 uM', 'dose: 11.1 uM', 'dose: 3.7 uM', 'dose: 1.2 uM', 'dose: 0.4 uM']

In [ ]:
#MAKE A DATAFRAME (TO INDEX INTO CHEMICAL OF INTEREST)
metadata_preview = pd.DataFrame({
    "sample_column": sample_desc,
    "chemical": sample_chem_row,
    "dose": sample_dose_row
})

metadata_preview.head()

              sample_column             chemical           dose
0  Corton-1-Rat-Primary_A07  chemical: triclosan  dose: 33.3 uM
1  Corton-1-Rat-Primary_A08  chemical: triclosan  dose: 11.1 uM
2  Corton-1-Rat-Primary_A09  chemical: triclosan   dose: 3.7 uM
3  Corton-1-Rat-Primary_A10  chemical: triclosan   dose: 1.2 uM
4  Corton-1-Rat-Primary_A11  chemical: triclosan   dose: 0.4 uM

In [25]:
#METADATA FOR SAMPLES WITH CHEMICAL OF INTEREST- S-BIOALLETHRIN
target_chemical = "S-bioallethrin"

s_bio_metadata = metadata_preview[
    metadata_preview["chemical"].str.contains(target_chemical, case=False, na=False)
].copy()

s_bio_metadata

                sample_column                  chemical           dose
135  Corton-2-Rat-Primary_E04  chemical: S-Bioallethrin   dose: 100 uM
136  Corton-2-Rat-Primary_E05  chemical: S-Bioallethrin  dose: 33.3 uM
137  Corton-2-Rat-Primary_E06  chemical: S-Bioallethrin  dose: 11.1 uM
138  Corton-2-Rat-Primary_E07  chemical: S-Bioallethrin   dose: 3.7 uM
139  Corton-2-Rat-Primary_E08  chemical: S-Bioallethrin   dose: 1.2 uM
140  Corton-2-Rat-Primary_E09  chemical: S-Bioallethrin   dose: 0.4 uM

In [26]:
#GET SAMPLE NAMES FOR CHEMICAL OF INTEREST
s_bio_sample_names = list(s_bio_metadata["sample_column"])

s_bio_sample_names

['Corton-2-Rat-Primary_E04',
 'Corton-2-Rat-Primary_E05',
 'Corton-2-Rat-Primary_E06',
 'Corton-2-Rat-Primary_E07',
 'Corton-2-Rat-Primary_E08',
 'Corton-2-Rat-Primary_E09']

In [29]:
expression_sample_columns = list(expression.columns[1:])

matching_sbio_samples = [
    sample for sample in s_bio_sample_names
    if sample in expression_sample_columns
]

missing_sbio_samples = [
    sample for sample in s_bio_sample_names
    if sample not in expression_sample_columns
]

print("S-bioallethrin samples in metadata:", len(s_bio_sample_names))
print("Matching samples in expression matrix:", len(matching_sbio_samples))
print("Missing samples:", len(missing_sbio_samples))

print("\nMissing sample names:")
print(missing_sbio_samples)

S-bioallethrin samples in metadata: 6
Matching samples in expression matrix: 6
Missing samples: 0

Missing sample names:
[]

ALL SAPLES WITH VARYING DOSES OF OUR TARGET CHEMICAL (S-BIOALLETHRIN) WERE IDENTIFIED IN THE SERIES MATRIX METADATA FILE.
BASED ON THE SAMPLE DESCRIPTION (SAMPLE NAMES),THE PRESENCE OF THOSE SAMPLES WAS ALSO IDENTIFIED IN THE EXPRESSION MATRIX FILE.